### ISSUE TITLE
[Bug]:  Error in loading config: No "exports" main defined

### ISSUE THREAD

**Issue by gausie** [Betanoir/medusa-variant-images#12]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When attempting to run the migration for (or just start medusa with) this plugin, I get the following error

```
error:   Error in loading config: No "exports" main defined in /Users/gausie/Projects/my_shop/node_modules/medusa-variant-images/package.json
error:   Error: No "exports" main defined in /Users/gausie/Projects/my_shop/node_modules/medusa-variant-images/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:314:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:661:9)
    at resolveExports (node:internal/modules/cjs/loader:653:36)
    at Function._findPath (node:internal/modules/cjs/loader:742:31)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1380:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/Users/gausie/Projects/neometrx/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._resolveFilename (/Users/gausie/Projects/neometrx/node_modules/tsconfig-paths/src/register.ts:115:36)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1050:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1055:22)
    at Function._load (node:internal/modules/cjs/loader:1204:37)
```

### Expected Behavior

The application starts successfully

### Anything else?

Extending my stack trace suggests that the error happens [here](https://github.com/medusajs/medusa/blob/69df00396864c5b86afc5316f9333e8aa32efb62/packages/core/utils/src/common/define-config.ts#L100).

I am guessing there is a CJS vs ESM issue. I am using node v23.7.0

**Comment by Betanoir** [comment]
Hi @gausie, does this occur when you are building the Medusa app for production or when normally starting it for development?

**Comment by gausie** [comment]
@Betanoir Definitely for development, let me just check building.

Yes, the same error happens during build

```
info:    Starting build...
info:    Compiling backend source...
info:    Removing existing ".medusa/server" folder
error:   Failed to load medusa-config.(js|ts) file
error:   No "exports" main defined in /Users/gausie/Projects/neometrx/node_modules/medusa-variant-images/package.json
Error: No "exports" main defined in /Users/gausie/Projects/neometrx/node_modules/medusa-variant-images/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:314:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:661:9)
    at resolveExports (node:internal/modules/cjs/loader:653:36)
    at Function._findPath (node:internal/modules/cjs/loader:742:31)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1380:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/Users/gausie/Projects/neometrx/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._resolveFilename (/Users/gausie/Projects/neometrx/node_modules/tsconfig-paths/src/register.ts:115:36)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1050:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1055:22)
    at Function._load (node:internal/modules/cjs/loader:1204:37) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

**Comment by Betanoir** [comment]
Okay, thanks!
I'll have a look at it later today.

**Comment by Betanoir** [comment]
Good day @gausie, I've opened an issue on Medusa's GitHub. I've tried a good few things in an attempt to fix this, but I remain unsuccessful. 

I'll keep you posted!

**Comment by gausie** [comment]
That's awesome thank you so much for your help

**Comment by Betanoir** [comment]
Hey @gausie, apologies for taking so long to get back to you. 
This issue is still very much here and many others are experiencing it on all different plugins. I do know what the issue is but I haven't had the time to open a PR on Medusa to push the fix. Either way, the fix would only come when Medusa releases a new update.

You could downgrade the version of Medusa and medusa-variant-images to a version lower and it should work in development then.

**Comment by Betanoir** [comment]
I have pushed a fix to Medusa, and the [PR](https://github.com/medusajs/medusa/pull/12418#issue-3050129190) has been merged. It will come in the next Medusa update!

**Comment by gausie** [comment]
Thank you so much!

**Comment by gausie** [comment]
Hey @Betanoir. Just upgraded to v2.8.0 which contains your PR, and I am still experiencing the issue

```
➜  neometrx-backend git:(main) ✗ yarn medusa --version
yarMedusa CLI version: 2.8.0
Medusa version: unknown
  Note: this is the Medusa version for the site at: /Users/gausie/Projects/neometrx/packages/neometrx-backend
n%                                                                                                                                                                               
➜  neometrx-backend git:(main) ✗ yarn medusa db:migrate
error:   Error in loading config: No "exports" main defined in /Users/gausie/Projects/neometrx/node_modules/medusa-variant-images/package.json
error:   Error: No "exports" main defined in /Users/gausie/Projects/neometrx/node_modules/medusa-variant-images/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:314:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:661:9)
    at resolveExports (node:internal/modules/cjs/loader:653:36)
    at Function._findPath (node:internal/modules/cjs/loader:742:31)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1380:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/Users/gausie/Projects/neometrx/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._resolveFilename (/Users/gausie/Projects/neometrx/node_modules/tsconfig-paths/src/register.ts:115:36)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1050:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1055:22)
    at Function._load (node:internal/modules/cjs/loader:1204:37)
```

**Comment by Betanoir** [comment]
Hey @gausie, I'll take a look at this tomorrow.

**Comment by Betanoir** [comment]
@gausie, could you do me a favour and check if this is happening with other plugins that have a widget in them?

**Comment by Betanoir** [comment]
Hi @gausie, I've just loaded the plugin on my end, and it seems to be working completely. I'm running `Medusa: ^2.8.2` and `medusa-variant-images: ^1.1.1`.

**Comment by Betanoir** [comment]
Should be resolved in `v1.1.2`

**Comment by renaudAmsellem** [comment]
Hey, i'm getting the same error with `medusa-variant-images: 1.1.2` and `Medusa: 2.8.3` or `2.8.2`.
I'm getting the error when running the project: `npm run dev` or by running the migrate command: `npx medusa db:migrate`

I haven't tried any other plugin though. Do you have an example i could try?

**Comment by Betanoir** [comment]
Hi @renaudAmsellem. I've just upgraded to the latest of both (`medusa-variant-images: 1.1.2` and `Medusa: 2.8.3`), and I can't seem to reproduce what you're getting.

This is my output with `npx medusa db:migrate`:
```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
info:    Migrations completed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

and with `yarn medusa --version`:
```
Medusa CLI version: 2.8.3
Medusa version: 2.8.3
  Note: this is the Medusa version for the site at: C:\
```

Could I suggest you delete your `node_modules` folder and `package-lock.json` and run `npm i` or `yarn` and then the necessary commands thereafter?

**Comment by renaudAmsellem** [comment]
Thanks for your answer.

I have tried with `npm v10.2.3`, `yarn v1.22.22`, `pnpm v10.11.1` ; each time deleting `package-lock.json` and `node_modules` but i keep getting the error.

My `node` version is: v20.10.0

Here's my `package.json` file:

[package.json](https://github.com/user-attachments/files/20599106/package.json)

**Comment by Betanoir** [comment]
No, thank you! Now I know what to respond with if this happens again in the future.

I'm glad it is working now.
